### ISSUE TITLE
could not provision a certificate on twistedmatrix.com

### ISSUE THREAD

**Issue by glyph** [mithrandi/txacme#110] opened 2017-03-23 09:14 UTC
We ran into a few issues.

First, https://github.com/glyph/txsni/issues/8 caused a lot of spurious noise and we needed to keep old, expired certificates around in order to trigger renewal attempts.  It would be good to get that fixed.

Then we got lots of these:

```
2017-03-23 01:00:40-0600 [-] PANIC! Unable to renew certificate for: u'twistedmatrix.com'
        Traceback (most recent call last):
          File "/srv/t-web/virtualenv/site-packages/treq/client.py", line 80, in _deliverWaiting
            waiter.connectionLost(reason)
          File "/srv/t-web/virtualenv/site-packages/treq/content.py", line 38, in connectionLost
            self.finished.callback(None)
          File "/srv/t-web/virtualenv/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/srv/t-web/virtualenv/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/srv/t-web/virtualenv/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/srv/t-web/virtualenv/site-packages/txacme/client.py", line 593, in repoll
            raise AuthorizationFailed(authzr)
        txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value=u'twistedmatrix.com') [Error(typ=u'urn:acme:error:connection', title=None, detail=u'Failed to connect to 66.35.39.66:443 for TLS-SNI-01 challenge')]>)
```

After hours of banging on fail2ban and otherwise attempting to figure out why it couldn't connect (you can try this yourself, that ip/port will happily respond from anywhere in the world _I_ have access to for TLS), we tried LETS, and got errors about CAA records instead.

Eventually I fell back to https://github.com/zenhack/simp_le and manually provisioned a cert with the http-01 challenge instead, and just installed that manually.  But it would be good to get to the bottom of this; at the very least, it would be nice to automate #31 for whatever case this is.

**Comment by glyph** [comment] 2017-03-23 09:14
@markrwilliams helped with this and might also have some insight.

**Comment by mithrandi** [comment] 2017-03-23 11:15
glyph/txsni#8 is somewhat of a red herring; you get this error from txsni if you touch an empty pem, and then a client tries to connect before txacme has issued a real cert for you, but it shouldn't affect the txacme issuance at all.

The problem with CAA records appears to be a bug in twistedmatrix.com's nameserver software:

```
mithrandi@lorien ~> host -t caa twistedmatrix.com ns1.twistedmatrix.com
Using domain server:
Name: ns1.twistedmatrix.com
Address: 66.35.39.66#53
Aliases:

Host twistedmatrix.com not found: 2(SERVFAIL)
mithrandi@lorien ~ [1]> host -t caa twistedmatrix.com ns2.twistedmatrix.com
Using domain server:
Name: ns2.twistedmatrix.com
Address: 104.239.227.92#53
Aliases:

Host twistedmatrix.com not found: 2(SERVFAIL)
```

The expected response to an unknown record type is an empty response, not `SERVFAIL`, which `host` will present like this:

```
mithrandi@lorien ~ [1]> host -t caa mithrandi.net
mithrandi.net has no CAA record
```

If I query for a different record type for which there are no records, for example:
```
mithrandi@lorien ~> host -t a6 twistedmatrix.com
twistedmatrix.com has no A6 record
```

Let's Encrypt does not require a CAA policy, but if it finds one for the domain in question, it will respect it, so I guess this failure to look it up constitutes a permanent failure in the authorization process.

**Comment by mithrandi** [comment] 2017-03-23 16:38
Closing this because there doesn't seem to be an active issue with txacme, but happy to continue discussing / diagnosing as needed.

**Closed by mithrandi** 2017-03-23 16:38 UTC

**Comment by glyph** [comment] 2017-03-24 03:13
> glyph/txsni#8 is somewhat of a red herring; you get this error from txsni if you touch an empty pem, and then a client tries to connect before txacme has issued a real cert for you, but it shouldn't affect the txacme issuance at all.

I don't think it was a red herring; in the configuration we were using (the `twisted-web` container) It caused a traceback that caused `twistd` to immediately exit.  It also seemed like in the other configuration (provisioning with a bare `twist web` instance) it caused issuance to fail to even be attempted.

**Comment by glyph** [comment] 2017-03-24 03:31
The main thing I want txacme to do here is allow me to fall back to the http-01 challenge without installing another piece of software.

**Comment by mithrandi** [comment] 2017-03-24 08:19
"Falling back" to the http-01 challenge isn't really possible with the endpoint as it stands; implementing http-01 requires hooking into your `Site` hierarchy, not your TLS protocol, so that's at a totally different level of the stack. You can do this by instantiating a `HTTP01Responder`, putting `.resource` in the right place for it to be served from `http://yourdomain.com/.well-known/acme-challenge`, and then instantiating an `AcmeIssuingService` with this responder; if you have any suggestions about making this easier, perhaps we should take those to another issue.

I'm not able to reproduce an empty file causing `twistd web` or `twist web` to exit on startup, even if issuing fails. For example:

```
$ twist web --port lets:/tmp/certs:tcp:4433 --path certs
2017-03-24T10:09:53+0200 [-] Site (TLS) starting on 4433
2017-03-24T10:09:53+0200 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x000055c8a0454160>
2017-03-24T10:09:53+0200 [txacme.service#info] Starting scheduled check for expired certificates.
2017-03-24T10:09:53+0200 [twisted.application.runner._runner.Runner#info] Starting reactor...
2017-03-24T10:09:53+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:53+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:53+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:53+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:54+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:55+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a07c8020>
2017-03-24T10:09:55+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a0777de0>
2017-03-24T10:09:55+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a0777de0>
2017-03-24T10:09:56+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a0777de0>
2017-03-24T10:09:56+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a0777de0>
2017-03-24T10:09:56+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x000055c8a0777de0>
2017-03-24T10:09:57+0200 [txacme.service#info] Found 1 overdue / expired and 0 expiring certificates.
2017-03-24T10:09:57+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00007f25db3914e0>
2017-03-24T10:09:57+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x00007f25db3914e0>
2017-03-24T10:09:58+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00007f25db3914e0>
2017-03-24T10:09:58+0200 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x00007f25db3914e0>
2017-03-24T10:09:58+0200 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00007f25db3914e0>
2017-03-24T10:09:59+0200 [txacme.service#info] Requesting a certificate for u'acme-testing-nonexistent.mithrandi.net'.
2017-03-24T10:10:01+0200 [txacme.service#critical] PANIC! Unable to renew certificate for: u'acme-testing-nonexistent.mithrandi.net'
        Traceback (most recent call last):
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/treq/client.py", line 80, in _deliverWaiting
            waiter.connectionLost(reason)
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/treq/content.py", line 38, in connectionLost
            self.finished.callback(None)
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/mithrandi/deployment/virtualenvs/tempenv-286d39431d6/site-packages/txacme/client.py", line 593, in repoll
            raise AuthorizationFailed(authzr)
        txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value=u'acme-testing-nonexistent.mithrandi.net') [Error(typ=u'urn:acme:error:connection', title=None, detail=u'DNS problem: NXDOMAIN looking up A for acme-testing-nonexistent.mithrandi.net')]>)
```

Trying to hit the server with curl during or after this process provokes the txsni bug, but this doesn't cause anything other than some harmless log messages as far as I can tell. Were you using the latest txacme and Twisted versions from PyPI, or something else?
